### ISSUE TITLE
Did you mean "Spec" instead of "Status"

### ISSUE THREAD

**Issue by mysterytony** [kubernetes/sample-controller#53]
https://github.com/kubernetes/sample-controller/blob/325dc0a18ed9c672755662fdcf9f0e71120ac30e/controller.go#L325-L330

Did you mean on L327, the "Spec"? But in the end you are not updating the Spec anyways, I suppose?

**Comment by devdattakulkarni** [comment]
@mysterytony No, the comment is correct. What it is referring to is the line 330. In that 'Update' method is used. The comment is saying that, instead of using the 'Update' method, more accurate would be to use the 'UpdateStatus' method since it is only the Status of the Custom Resource that we want to update. 'UpdateStatus' will update on the status and nothing else. With 'Update' it is programmer's responsibility to ensure that only the Status field is updated and not any part of the Spec, even accidentally.
However, for using 'UpdateStatus' the feature gate mentioned in the comment on line 326 needs to be enabled on the API Server. Ideally, the code could be written such that it checks if the gate is enabled and then decides whether to use 'Update' or 'UpdateStatus'. For now, the comment is referring to all of this and leaving the potential for improvement open.

**Comment by mysterytony** [comment]
@devdattakulkarni I see. Thank you!

Closing now.
