### ISSUE TITLE
code is not generated to correct dir

### ISSUE THREAD

**Issue by silentred** [kubernetes/sample-controller#96]
My sample-controller project is at `/Users/jason/Desktop/projects/sample-controller`.
I checked out tag `release-1.24`, run`go mod vendor`, finally run `./hack/update-codegen.sh` in the project root.
I found the code was generated at `/Users/jason/Desktop/k8s.io/sample-controller/pkg/generated`.

Expectation: Codes should be generated at `/Users/jason/Desktop/projects/sample-controller/pkg/generated`

![image](https://github.com/kubernetes/sample-controller/assets/3345293/a059ecfb-5935-445e-a4bf-922a74e86198)

**Comment by fxierh** [comment]
I encountered the same issue. 

I believe the root cause is [this](https://github.com/kubernetes/code-generator/blob/a46324df52090722a7341d1255ed47e31ea6b182/kube_codegen.sh#L122-L123) where `go list -find .` gives a module-name-based (instead of folder-path-based) path (`k8s.io/sample-controller...`) which is then passed (as `--input-dirs`) to `deepcopy-gen`.
